eureka:
  client:
      client:
        serviceUrl:
          defaultZone: http://localhost:8076/eureka



##      default-zone: http://localhost:8076/eureka
#
#
##    register-with-eureka: true
##    fetch-registry: true
#
##
#spring:
#  application:
#    name: api-gateway
##
server:
  port: 9096
#
#
#
#
#  -spring:
#    cloud:
#      gateway:
#        routes:
#          id: authentication-service
#          uri: https://localhost:8992/
#          predicates:
#            - Path=/authentication/**
#          filters:
#            - RewritePath=/authentication(?<segment>/?.*),$\{segment}
#
#
#  spring:
#    cloud:
#    gateway:
#      routes:
#        id: chat-service
#        uri: https://localhost:8787/
#        predicates:
#          - Path=/chat/**
#        filters:
#            - RewritePath=/chat(?<segment>/?.*),$\{segment}
#
#  ---spring:
#    cloud:
#      gateway:
#        routes:
#          id: config-service
#          uri: https://localhost:8888/
#          predicates:
#            - Path=/config/**
#          filters:
#              - RewritePath=/config(?<segment>/?.*),$\{segment}
#
#
#
#  -- spring:
#    cloud:
#      gateway:
#        routes:
#          id: email-service
#          uri: https://localhost:8082/
#          predicates:
#            - Path=/email/**
#          filters:
#            - RewritePath=/email(?<segment>/?.*),$\{segment}
#
#
#  --- spring:
#    cloud:
#      gateway:
#        routes:
#          id: enrollemnt-service
#          uri: https://localhost:8080/
#          predicates:
#            - Path=/enrollment/**
#          filters:
#            - RewritePath=/enrollment(?<segment>/?.*),$\{segment}
#
#  --spring:
#    cloud:
#      gateway:
#        routes:
#          id: payment-service
#          uri: https://localhost:8060/
#          predicates:
#            - Path=/payment/**
#          filters:
#            - RewritePath=/payment(?<segment>/?.*),$\{segment}
#
#-spring:
#  cloud:
#    gateway:
#      routes:
#        id: session-service
#        uri: https://localhost:9090/
#        predicates:
#          - Path=/session/**
#        filters:
#          - RewritePath=/session(?<segment>/?.*),$\{segment}
#
#
#-- spring:
#  cloud:
#    gateway:
#      routes:
#        id: student-service
#        uri: https://localhost:8889/
#        predicates:
#          - Path=/student/**
#        filters:
#            - RewritePath=/student(?<segment>/?.*),$\{segment}
#
#
#  spring:
#    cloud:
#      gateway:
#        routes:
#          id: tutor-service
#          uri: https://localhost:8989/
#          predicates:
#            - Path=/tutor/**
#          filters:
#            - RewritePath=/tutor(?<segment>/?.*),$\{segment}

spring:
  application:
    name: "API-Gateway"
  main:
    web-application-type: reactive
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            exposedHeaders: "*"
      routes:
        - id: Authentication-service
          uri: https://localhost:8992/
          predicates:
            - Path=/api/v1/Authentication-service/**



        - id: Tutor-service
          uri: http://localhost:8989/
          predicates:
            - Path=/api/v1/Tutor-service/**

        - id: Student-service
          uri: http://localhost:8889/
          predicates:
            - Path=/api/v1/Student-service/**



        - id: Session-service
          uri: http://localhost:9090/
          predicates:
            - Path=/api/v1/Session-service/**


        - id: Enrollment-service
          uri: http://localhost:8080/
          predicates:
            - Path=/api/v1/Enrollment-service/**

        - id: Payment-Service
          uri: http://localhost:8060/
          predicates:
            - Path=/api/v1/Payment-Service/**

        - id: Email-service
          uri: http://localhost:8082/
          predicates:
            - Path=/api/v1/Email-service/**

        - id: Chat-service
          uri: http://localhost:8787/
          predicates:
            - Path=/api/v1/Chat-service/**
      config:
        uri: http://localhost:8080
        fail-fast: false
        retry:
          maxAttempts: 20


      logging:
        level:
          '[org.springframework.cloud.gateway]': TRACE

